M48
; DRILL file {KiCad 9.0.3} date 2025-12-07T17:58:32-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-07T17:58:32-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X8.3573Y-4.201
X8.3573Y-4.4285
T2
X7.6187Y-2.3008
X7.7368Y-2.3008
T3
X7.1891Y-6.0744
X7.5041Y-6.0744
M30
